version: "3.8"

services:
  catalog:
    image: bazar/catalog:latest
    ports:
      - "3001:3001"
    volumes:
      - catalog-data:/app/catalog.csv
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://frontend:3002
    networks:
      - bazar-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M

  order:
    image: bazar/order:latest
    ports:
      - "3000:3000"
    volumes:
      - order-data:/app/orders.csv
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CATALOG_SERVICE_URL=http://catalog:3001
      - FRONTEND_URL=http://frontend:3002
    depends_on:
      - catalog
    networks:
      - bazar-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  frontend:
    image: bazar/frontend:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - CATALOG_SERVICE_URL=http://catalog:3001
      - ORDER_SERVICE_URL=http://order:3000
    depends_on:
      - catalog
      - order
    networks:
      - bazar-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  bazar-network:
    driver: overlay
    attachable: true

volumes:
  catalog-data:
    driver: local
  order-data:
    driver: local
